# Generated by Django 3.0.1 on 2019-12-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_name', models.CharField(max_length=200)),
                ('processor_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RAMType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_name', models.CharField(max_length=200)),
                ('ram_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MainBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=200)),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_manager.Processor')),
                ('ram_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts_manager.RAMType')),
            ],
        ),
    ]
